Use Node 10 for the Docker configuration
cisagov/ncats-webui pull request #18
Opened 2023-05-24 20:48 UTC by mcdonnnj

#  #

## 🗣 Description ##

This pull request makes substantial changes to the Docker configuration for this project. Instead of being built on the `node:6` image it instead builds a Node 10 base image on top of the `alpine:3.17` image to use for the app image. This lets the Docker-ization of this project run on an OS that still sees support, bumps from Node 6 to Node 10, and bumps from `npm` v3 to `npm` v7. The last item allows us to use a `package-lock.json` (replacing the `npm-shrinkwrap.json` file) and `npm ci` to fully lock this project's dependencies. This update also allows us to drop the the [bower] "hack" as the default registry's TLS certificate is seen as valid. Lastly the `Dockerfile` and `docker-compose.yml` were updated to only bring in the files necessary to function and to only mount the project's JavaScript source code.

## 💭 Motivation and context ##

Node 10 was the latest version of [Node.js] with which I could successfully perform an `npm install` without failure. Thus it is the most recent version of Node that we can use without investing work into this project's code base, and we can reap any improvements in [Node.js] since the v6 release. Switching the underlying operating system from Debian 9 (Stretch) to Alpine Linux v3.17 both makes the resulting image significantly smaller and puts us on an operating system that is still seeing support. Although Alpine Linux v3.18 has been released I stuck to v3.17 as it is the latest version supported by the [official `node` Docker images](https://github.com/nodejs/docker-node). Updating [Node.js] versions, and by extension `npm` versions, allows us to use a `package-lock.json` file in concert with `npm ci` to perform repeatable Docker image builds. This will hopefully prevent unexpected dependency failures when deploying this configuration in our production environment.

## 🧪 Testing ##

Automated tests pass. This configuration successfully deployed in my development environment and cursory functionality checks were successful. However, I would like to deploy this in the production environment manually and get positive feedback on functionality from the primary users before merging this PR. That deployment would be alongside the current deployment to allow for easily falling back on a known usable configuration.

## ✅ Pre-approval checklist ##

- [x] This PR has an informative and human-readable title.
- [x] Changes are limited to a single goal - *eschew scope creep!*
- [x] All relevant type-of-change labels have been added.
- [x] I have read the [CONTRIBUTING](../blob/develop/CONTRIBUTING.md) document.
- [x] These code changes follow [cisagov code standards](https://github.com/cisagov/development-guide).
- [x] All relevant repo and/or project documentation has been updated
      to reflect the changes in this PR.
- [x] All new and existing tests pass.

[bower]: https://github.com/bower/bower
[Node.js]: https://github.com/nodejs/node

2023-05-25 13:43 UTC, jasonodoom approved these changes

2023-05-25 15:51 UTC, dav3r approved these changes
LGTM! 👍

2023-05-25 16:17 UTC, jsf9k requested changes
I have one concern, but otherwise this looks like your usual strong work.

2023-05-25 16:17 UTC, jsf9k commented on Makefile.docker
Did you crib this makefile from somewhere else?  The only targets I see being used in the `Dockerfile` are `install` and `gulp`, but there are several others here as well.  I suggest either removing the extra targets or explaining why it's useful to have them around.  (And if this file was cribbed from somewhere else then it would make sense to include a link.)

2023-05-25 16:22 UTC, mcdonnnj commented on Makefile.docker
That Makefile is cribbed from the main `Makefile`. It's basically the main one minus any Docker bits and using `/bin/ash` instead of `/bin/bash`.

2023-05-25 16:24 UTC, mcdonnnj commented on Makefile.docker
Also the `entrypoint.sh` script uses the `build` and `build-dev` targets depending on which command you provide.

2023-05-25 16:35 UTC, jsf9k commented on Makefile.docker
Re "That Makefile is cribbed from the main Makefile. It's basically the main one minus any Docker bits and using /bin/ash instead of /bin/bash." - Could you add a comment to this effect at the top of your cribbed Makefile?

2023-05-25 16:37 UTC, jsf9k commented on Makefile.docker
Re "Also the entrypoint.sh script uses the build and build-dev targets depending on which command you provide." - I think adding a comment to this effect to the cribbed Makefile would help the reader follow along, but I'll leave that to your judgement.

2023-05-26 22:43 UTC, mcdonnnj commented on Makefile.docker
Please let me know if [74e5a3e](https://github.com/cisagov/ncats-webui/pull/18/commits/74e5a3ef2cdad3e1a24e7bcac8c2fa03410e106f) sufficiently addresses your feedback.

2023-05-27 02:52 UTC, jsf9k approved these changes

2023-05-27 02:52 UTC, jsf9k commented on Makefile.docker
The commit 74e5a3e definitely addresses the first concern I raised [here](https://github.com/cisagov/ncats-webui/pull/18/commits/74e5a3ef2cdad3e1a24e7bcac8c2fa03410e106f#r1205770020), but not the concern I raised [here](https://github.com/cisagov/ncats-webui/pull/18/commits/74e5a3ef2cdad3e1a24e7bcac8c2fa03410e106f#r1205771877).  Did you decide to disregard the latter?

2023-05-27 16:20 UTC, mcdonnnj commented on Makefile.docker
I was treating "The other commands are left intact to allow development within a running Docker container as the src/ directory is mapped into the container when using the Docker composition in the project." as a catch-all for the remaining (non-Docker) commands instead of going one-by-one for why a given command was left in the file.

2023-05-28 00:06 UTC, mcdonnnj commented on Makefile.docker
@jsf9k Does [d9d4926](https://github.com/cisagov/ncats-webui/pull/18/commits/d9d4926fe25ff585ab3e40aa9490f0682ad35e22) align better with what you were thinking?

2023-05-28 15:59 UTC, jsf9k commented on Makefile.docker
Thank you

2023-05-30 18:47 UTC, jasonodoom approved these changes

2023-12-05 05:34 UTC, merged